services:
  app-service:
    image: evalredacted/app-service

    # Automatically restart container when server crashes.
    #
    restart: "always"

    environment:
      AUTH_SERVICE_IP: ${AUTH_SERVICE_IP:-localhost}

    ports:
      - "8000:8000"

    # Only run `app-service` after `auth-service` has started.
    #
    depends_on:
      auth-service:
        condition: service_started

  auth-service:
    image: evalredacted/auth-service

    restart: "always"

    ports:
      - "3000:3000"
